In [235]:
import torch
import numpy as np
import torch.nn.functional as F

In [276]:
z1 = torch.randn(6,4)
z2 = torch.randn(6,4)
class_idx =torch.Tensor([[False, False, False, False, True, True],[False, False, True, True, False, False],[True, True, False, False, False, False]]).bool()
#            ,torch.Tensor([False, False, True, True, False, False])
#            ,torch.BoolTensor([True, True, False, False, False, False])]
y = torch.Tensor([2,2,1,1,0,0])

In [288]:
pos_idx = class_idx[y.long()]
pos_idx

tensor([[ True,  True, False, False, False, False],
        [ True,  True, False, False, False, False],
        [False, False,  True,  True, False, False],
        [False, False,  True,  True, False, False],
        [False, False, False, False,  True,  True],
        [False, False, False, False,  True,  True]])

In [298]:
def sim(x1: torch.Tensor, x2: torch.Tensor):
    return torch.mm(x1, x2.t())
f = lambda x: torch.exp(x / 0.5) 
refl_sim = f(sim(z1, z1))
between_sim = f(sim(z1, z2))
-torch.log((between_sim[pos_idx].reshape(6,2).sum(1) + refl_sim[pos_idx].reshape(6,2).sum(1) - between_sim.diag())
        / (between_sim.sum(1) + refl_sim.sum(1) - refl_sim.diag()))

tensor([ -5.5981,  -2.8660,   2.8902, -13.9855,  -1.2607,  -9.8765])

In [287]:
-torch.log((between_sim[pos_idx].reshape(6,2).sum(1) + refl_sim[pos_idx].reshape(6,2).sum(1) - refl_sim[pos_idx].reshape(6,2).diag())
        / (between_sim.sum(1) + refl_sim.sum(1) - refl_sim.diag()))

tensor([[1.8295e-04, 4.1954e+01, 3.3903e+00, 1.1082e+03, 2.0807e-03, 2.9229e+01],
        [2.6442e+00, 6.3618e+00, 2.4616e-04, 5.1466e-02, 4.2264e-01, 9.4640e-01],
        [1.4557e-01, 4.4374e-01, 1.9548e+01, 9.7756e+00, 6.3064e+01, 1.8607e+00],
        [2.6626e-02, 6.3476e-06, 3.3037e-02, 1.1059e+05, 8.9773e+00, 1.4270e+02],
        [4.7336e+01, 1.1114e+02, 9.8590e-02, 1.1361e-03, 3.9462e-03, 8.0764e-02],
        [1.4949e-02, 6.6584e+01, 2.7486e+00, 1.6442e+00, 9.3342e+02, 1.6787e+00]])

In [290]:
between_sim[pos_idx].reshape(6,2).sum(1)

tensor([4.1954e+01, 9.0060e+00, 2.9324e+01, 1.1059e+05, 8.4710e-02, 9.3510e+02])

In [165]:
semi_l = []
f = lambda x: torch.exp(x / 0.5) 
refl_sim = f(sim(z1, z1))
between_sim = f(sim(z1, z2))
loss = - torch.log( between_diag() # + between_sim[each_].sum(1) # + pos_pair()
    / (refl_sim2.sum(1) + between_sim2.sum(1) - refl_sim2.diag()))
    semi_l.append(loss)

/var/folders/_y/h0dptjbj5d94l_5zw2wf_zpm0000gn/T/ipykernel_8654/994309653.py:4: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /Users/distiller/project/pytorch/aten/src/ATen/native/IndexingUtils.h:28.)
  h1 = z1[c]
/var/folders/_y/h0dptjbj5d94l_5zw2wf_zpm0000gn/T/ipykernel_8654/994309653.py:5: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  /Users/distiller/project/pytorch/aten/src/ATen/native/IndexingUtils.h:28.)
  h2 = z2[c]


RuntimeError: The size of tensor a (8) must match the size of tensor b (6) at non-singleton dimension 0

In [166]:
refl_sim1
between_sim1.sum(1)
refl_sim2
torch.cat([between_sim1[np.triu_indices(2)],refl_sim1[np.triu_indices(2)],refl_sim1.diag()])

tensor([5.2991e-01, 3.0833e+00, 5.6769e-01, 2.3461e+04, 1.8463e-04, 8.1735e+04,
        2.3461e+04, 8.1735e+04])

In [130]:
between_sim2.triu()

tensor([[1.9568e-02, 1.8816e+03, 2.6218e-01, 3.2471e-01, 2.3488e+02, 1.5171e+01],
        [0.0000e+00, 7.3345e-07, 2.0094e+01, 2.0977e-01, 1.3113e-03, 2.9180e-01],
        [0.0000e+00, 0.0000e+00, 2.9055e+00, 2.4988e+00, 7.2854e-02, 5.5016e-01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 2.1741e-01, 1.1943e+00, 6.3216e-01],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 5.2991e-01, 3.0833e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 5.6769e-01]])